version: "3.8"

services:
  localstack:
    image: localstack/localstack:0.11.6
    container_name: localstack
    environment:
      SERVICES: "s3"
      TMPDIR: "/tmp"
      DATA_DIR: "/var/opt/data"
      DEFAULT_REGION: "ap-northeast-1"
      AWS_DEFAULT_REGION: "ap-northeast-1"
      AWS_ACCESS_KEY_ID: "access_key_id_localstack"
      AWS_SECRET_ACCESS_KEY: "secret_access_key_localstack"
      LOCALSTACK_S3_BUCKET: "local-test"
    volumes:
      - lsdata:/var/opt/data
      - ./localstack/init.sh:/docker-entrypoint-initaws.d/init.sh
    ports:
      - 4566:4566
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  logstash:
    build: ./logstash
    container_name: logstash
    tty: true
    environment:
      LOGSTASH_INPUT_S3_AWS_ENDPOINT: "http://localstack:4566"
      LOGSTASH_INPUT_S3_AWS_ACCESS_KEY_ID: "access_key_id_localstack"
      LOGSTASH_INPUT_S3_AWS_SECRET_ACCESS_KEY: "secret_access_key_localstack"
      LOGSTASH_INPUT_S3_SINCEDB: "/tmp/var/lib/logstash/sincedb"
      LOGSTASH_INPUT_S3_FORCE_PATH_STYLE: "true"
      LOGSTASH_OUTPUT_ES_HOST: "http://elasticsearch:9200"
    depends_on:
      - localstack
      - elasticsearch
    volumes:
      - ./logstash/sincedb:/tmp/var/lib/logstash/sincedb
    ports:
      - 9600:9600
    links:
      - localstack:localstack
      - elasticsearch:elasticsearch
    networks:
      - esnet

networks:
  esnet:
    driver: bridge

volumes:
  lsdata:
    driver: local
  esdata:
    driver: local

